services:
  # Backend API service
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:///./space_cargo.db
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - space-cargo-network

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - space-cargo-network

# Network configuration
networks:
  space-cargo-network:
    driver: bridge