# Generated by Django 5.2 on 2025-04-07 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width_cm', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('depth_cm', models.FloatField()),
                ('max_weight_kg', models.FloatField()),
                ('zone', models.CharField(max_length=50)),
                ('used_volume', models.FloatField(default=0)),
                ('used_weight', models.FloatField(default=0)),
                ('is_full', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width_cm', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('depth_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('priority', models.IntegerField(default=1)),
                ('preferred_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_placed', models.BooleanField(default=False)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('position_z', models.FloatField(blank=True, null=True)),
                ('rotation', models.IntegerField(blank=True, null=True)),
                ('placement_date', models.DateTimeField(blank=True, null=True)),
                ('sensitive', models.BooleanField(default=False)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='placement.container')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.container')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.item')),
            ],
        ),
    ]
